name: Check Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  ETHPLORER_API_KEY: ${{ secrets.ETHPLORER_API_KEY }}

jobs:
  bash:
    runs-on: ubuntu-latest

    steps:
      - name: Check ETHPLORER_API_KEY
        run: |
          if [ -z "$ETHPLORER_API_KEY" ] ; then
            echo "Missing ENV variable ETHPLORER_API_KEY"
            exit 1
          fi

      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check all files
        run: bash ./check.sh
