name: Check Files (complete)
on:
  push:
    branches:
      - master
env:
  ETHPLORER_API_KEY: ${{ secrets.ETHPLORER_API_KEY }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check ETHPLORER_API_KEY
        run: |
          if [ -z "$ETHPLORER_API_KEY" ] ; then
            echo "Missing ENV variable ETHPLORER_API_KEY"
            exit 1
          fi

      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip install -r tests/requirements.txt

      - name: Check address checksum
        run: python tests/check_checksum.py

      - name: Check tokens
        run: python tests/check_token.py

